baseURL = 'https://rogemus.github.io/'
languageCode = 'pl-pl'
title = "Rogemus - Felietony o grach i absurdach"
theme = "rogtheme"
enableRobotsTXT = true
disqusShortname = "rogemus"

[taxonomies]
  series = 'series'

[params]
  mainSections = ["posts"]
  description = "O grach, o absurdach i jeszcze raz o grach - felietony i marudzenie na wszystko, byście wy nie musieli."
  author = 'Kacper "Rogemus" Rogowski'
  images = ["social-card.png"]

  [params.social]
    twitter = "rogemus"
    twitter_enable = true
    twitch = "rogemus"
    twitch_eneble = false
    facebook = ""
    facebook_enable = false
    rss_enable = true

[menu]
  [[menu.main]]
    identifier = "o-mnie"
    name = "O Mnie"
    url = "/o-mnie/"
    weight= 5

  [[menu.footer]]
    identifier = "o-mnie"
    name = "O Mnie"
    url = "/o-mnie/"
    weight= 5