baseURL = 'https://rogemus.github.io/'
languageCode = 'pl-pl'
title = "Rogemus"
theme = "rogtheme"
description = "This is my awesome blog"
enableRobotsTXT = true

[params]
  mainSections = ["posts"]

  [params.social]
    twitter = "rogemus"
    twitch = "rogemus"
    facebook = ""

[menu]
  [[menu.main]]
    identifier = "o-mnie"
    name = "O Mnie"
    url = "/o-mnie/"
    weight= 5
  [[menu.main]]
    identifier = "absurdy"
    name = "Absurdy"
    url = "/categories/absurdy/"
    weight= 10